//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR_PARTS_ORDERED
    {
        public int ORD_ID { get; set; }
        public int CARPARTS_ID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public int CARPARTSORDEREDID { get; set; }
    
        public virtual CAR_PARTS CAR_PARTS { get; set; }
        public virtual ORDER ORDER { get; set; }
    }
}
