//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFER
    {
        public int OFFER_ID { get; set; }
        public int CAR_ID { get; set; }
        public int CLIENT_ID { get; set; }
        public int SALES_ID { get; set; }
        public int STATUS_ID { get; set; }
        public int OFFERTYPE_ID { get; set; }
        public Nullable<double> AMOUNT { get; set; }
    
        public virtual CAR CAR { get; set; }
        public virtual CLIENT CLIENT { get; set; }
        public virtual OFFER_STATUS OFFER_STATUS { get; set; }
        public virtual OFFER_TYPE OFFER_TYPE { get; set; }
        public virtual SALE SALE { get; set; }
    }
}
