//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.ACCESSes = new HashSet<ACCESS>();
            this.CLIENTs = new HashSet<CLIENT>();
        }
    
        public int USER_ID { get; set; }
        public int USERROLE_ID { get; set; }
        public string FULL_NAME { get; set; }
        public string EMAIL { get; set; }
        public string ADDRESS { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> AVAILABLEDAYS { get; set; }
        public Nullable<System.DateTime> AVAILABLETIMES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCESS> ACCESSes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENT> CLIENTs { get; set; }
        public virtual USER_ROLE USER_ROLE { get; set; }
    }
}
