//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehlution_Everything_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR_BOOKING
    {
        public int CARBOOKING_ID { get; set; }
        public int CAR_ID { get; set; }
        public int USER_ID { get; set; }
        public string STATUS { get; set; }
        public int CAR_BOOKING_SLOTS_ID { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual CAR_BOOKING CAR_BOOKING1 { get; set; }
        public virtual CAR_BOOKING CAR_BOOKING2 { get; set; }
        public virtual CAR_BOOKING_SLOTS CAR_BOOKING_SLOTS { get; set; }
        public virtual CAR_BOOKING CAR_BOOKING11 { get; set; }
        public virtual CAR_BOOKING CAR_BOOKING3 { get; set; }
    }
}
