//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehlution_Everything_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_SATISFACTION
    {
        public int RateID { get; set; }
        public Nullable<int> Experience { get; set; }
        public Nullable<int> Recommendation { get; set; }
        public Nullable<int> Website { get; set; }
        public Nullable<int> ResponseTime { get; set; }
        public Nullable<int> CustomerComms { get; set; }
    }
}
