//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehlution_Everything_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENT_TYPE
    {
        public int DOCUMENTTYPE_ID { get; set; }
        public int DOCUMENT { get; set; }
        public string DOCUMENTTYPE_NAME { get; set; }
    
        public virtual CLIENT_DOCUMENTS CLIENT_DOCUMENTS { get; set; }
    }
}
