//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehlution_Everything_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLYEE_SALES
    {
        public int EMPLYEE_ID { get; set; }
        public int SALES_ID { get; set; }
        public int EMPLOYEESALESID { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual SALE SALE { get; set; }
    }
}
