//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehlution_Everything_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE_LOGS
    {
        public int SALES_ID { get; set; }
        public string PAYMENT_ID { get; set; }
        public string OFFER_ID { get; set; }
        public string SALE_DATE { get; set; }
        public string ACCEPTED_OFFER { get; set; }
        public string CAR_CONTRACT { get; set; }
        public string AUDITID { get; set; }
        public string AUDITACTION { get; set; }
        public string AUDITDATE { get; set; }
        public string AUDITUSER { get; set; }
    }
}
