//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehlution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEFECT_STATUS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEFECT_STATUS()
        {
            this.CAR_DEFECT_STATUS = new HashSet<CAR_DEFECT_STATUS>();
        }
    
        public int STATUS_ID { get; set; }
        public string STATUS_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAR_DEFECT_STATUS> CAR_DEFECT_STATUS { get; set; }
    }
}
