//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehlution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MECHANIC_JOB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MECHANIC_JOB()
        {
            this.MECHANIC_TASK = new HashSet<MECHANIC_TASK>();
        }
    
        public int MECHANICJOB_ID { get; set; }
        public int CAR_ID { get; set; }
        public Nullable<int> MECHANIC_ID { get; set; }
        public Nullable<System.DateTime> JOB_DATE { get; set; }
        public Nullable<System.DateTime> JOB_TIME { get; set; }
    
        public virtual CAR CAR { get; set; }
        public virtual MECHANIC MECHANIC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MECHANIC_TASK> MECHANIC_TASK { get; set; }
    }
}
