//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehlution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MECHANIC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MECHANIC()
        {
            this.MECHANIC_JOB = new HashSet<MECHANIC_JOB>();
        }
    
        public int MECHANIC_ID { get; set; }
        public string FULL_NAME_ { get; set; }
        public string CELL_NUMBER_ { get; set; }
        public string EMAIL_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MECHANIC_JOB> MECHANIC_JOB { get; set; }
    }
}
