//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELATIONSHIP_12
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RELATIONSHIP_12()
        {
            this.MECHANIC_TASK = new HashSet<MECHANIC_TASK>();
        }
    
        public int CARPARTS_ID { get; set; }
        public int CARPARTSUSEDID { get; set; }
    
        public virtual CAR_PARTS CAR_PARTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MECHANIC_TASK> MECHANIC_TASK { get; set; }
    }
}
