//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING_FOR_POSSIBLE_PURCHASE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOKING_FOR_POSSIBLE_PURCHASE()
        {
            this.CARS = new HashSet<CAR>();
        }
    
        public int CLIENT_ID { get; set; }
        public int STATUS_ID { get; set; }
        public int BOOKING_ID { get; set; }
        public Nullable<System.DateTime> BOOKING_DATE { get; set; }
        public Nullable<System.DateTime> BOOKING_TIME { get; set; }
        public string BOOKING_STATUS { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual POSSIBLE_PURCHASE_STATUS POSSIBLE_PURCHASE_STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAR> CARS { get; set; }
    }
}
