//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT_DOCUMENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT_DOCUMENTS()
        {
            this.DOCUMENT_TYPE = new HashSet<DOCUMENT_TYPE>();
        }
    
        public int DOCUEMTN_ID { get; set; }
        public int CLIENT_ID { get; set; }
        public int DOCUMENTTYPE_ID { get; set; }
        public string DOCUMENT { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENT_TYPE> DOCUMENT_TYPE { get; set; }
    }
}
