//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MECHANIC
    {
        public int MECHANIC_ID { get; set; }
        public int MECHANICJOB_ID { get; set; }
        public string FULL_NAME_ { get; set; }
        public string CELL_NUMBER_ { get; set; }
        public string EMAIL_ { get; set; }
    
        public virtual MECHANIC_JOB MECHANIC_JOB { get; set; }
    }
}
