//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR_PARTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAR_PARTS()
        {
            this.CAR_PARTS_ORDERED = new HashSet<CAR_PARTS_ORDERED>();
        }
    
        public int CARPARTS_ID { get; set; }
        public string PARTNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAR_PARTS_ORDERED> CAR_PARTS_ORDERED { get; set; }
        public virtual RELATIONSHIP_12 RELATIONSHIP_12 { get; set; }
    }
}
