//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.SALES = new HashSet<SALE>();
        }
    
        public int EMPLYEE_ID { get; set; }
        public int TIME_ID { get; set; }
        public int DAY_ { get; set; }
        public string FULL_NAME { get; set; }
        public string CELL_NUMBER { get; set; }
        public string EMAIL { get; set; }
        public string JOB_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> DATE_HIRED { get; set; }
    
        public virtual CAR_BOOKING_SLOTS CAR_BOOKING_SLOTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE> SALES { get; set; }
    }
}
